apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: clusterman-deployment
spec:
  selector:
    matchLabels:
      app: clusterman
  replicas: 1 
  template:
    metadata:
      labels:
        app: clusterman
    spec:
      containers:
      - name: clusterman
        image: sangho/clusterman
        imagePullPolicy: Always
        ports:
        - containerPort: 9191
---
apiVersion: v1
kind: Service
metadata:
  name: clusterman-service
spec:
  ports:
  - port: 9191
    name: rest
  selector:
    app: clusterman
